name: Deploy Preview
on: pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create temp serviceAccount.json
        run: echo "{}" > serviceAccount.json
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # See docs/tutorials/04-deploy.md for configuring these
          projectId: gdg-warsaw-devfest23-web-11997
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDG_WARSAW_DEVFEST23_WEB_11997 }}'
